### ISSUE TITLE
where is the dataset for the example of sampling.py ?

### ISSUE THREAD

**Issue by loveJasmine** [inspirehep/beard#101]
python sampling.py \
    --input_signatures input/signatures.json \
    --input_clusters input/clusters.json \
    --balanced 1 \
    --sample_size 1000000 \
    --output_pairs pairs/1M_nysiis_balanced.json \
    --use_blocking 1 \
    --blocking_function block_phonetic \
    --blocking_threshold 1 \
    --blocking_phonetic_alg nysiis \
    --verbose 1

**Comment by MSusik** [comment]
I believe you are looking for https://github.com/glouppe/paper-author-disambiguation
