### ISSUE TITLE
general: parametrized tests are not runnable with nosetests

### ISSUE THREAD

**Issue by glouppe** [inspirehep/beard#17]
Not that it is strictly required, but the use of `pytest.mark.parametrize` makes it not possible to run the corresponding decorated tests with nosetests. 

Ideas @MSusik @petros-ioannidis  ?

**Comment by MSusik** [comment]
I think that there is no such way to parametrize tests in `nose`. So the question is whether we should drop support for `nose` or drop parametrizing?

**Comment by glouppe** [comment]
Well, you can do something similar, by writing a test generator. I am not sure this is supported by py.test though, we should check.

**Comment by petros-ioannidis** [comment]
I think there are alternatives for parameterizing in nose so we shouldn't
drop parameterizing since its helpful for tests. I did not search
thoroughly but I think we can write our own test generator that will be
compatible or just use another method for parameterizing.

**Comment by glouppe** [comment]
In nose, this can be done using something similar to https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/ensemble/tests/test_forest.py#L102

I dont know if such tests are compatible with py.test though. This is something to be checked.

**Comment by MSusik** [comment]
Might be relevant;
http://pytest.org/2.2.4/example/parametrize.html#a-quick-port-of-testscenarios

**Comment by MSusik** [comment]
Closing, as Pytest is nowadays the standard
