### ISSUE TITLE
Make first release

### ISSUE THREAD

**Issue by kaplun** [inspirehep/beard#79]
After applying useful goodies from inveniosoftware/cookiecutter-invenio-module, we need to push to pypi beard-0.1.0 so that we have a stable version to start working on.

**Comment by glouppe** [comment]
This package is independent of Invenio and should stay like this in my opinion. What do you want to apply from the cookiecutter module?

**Comment by kaplun** [comment]
E.g. the `checkmanifest` part, https://github.com/inveniosoftware/cookiecutter-invenio-module/blob/master/%7B%7B%20cookiecutter.project_shortname%20%7D%7D/run-tests.sh. Additionally by having all the package functionalities the most compatible with cookiecutter would allows future maintainer to apply quickly other new integration should they arise.

**Comment by jirikuncar** [comment]
@kaplun :+1: for keeping the structure, testing and release processes as close as possible to other `inveniosoftware` packages. We are applying same principles to `Flask-*`, `dictdiffer`, `dojson` packages and personally I don't see a reason why `beard` should do them differently. If there are some new cool improvements, please consider contributing them back to `cookiecutter-invenio-module`.

**Comment by glouppe** [comment]
@kaplun Please submit a PR with proposed changes then. As long as beard remains easy to use, install and maintain, I am fine with that.

**Comment by jalavik** [comment]
Depending if #84 is ready soon, shall we make an initial release? To save time, I don't think any specific goodies is needed for the initial release as long as it is green.

Cause, it would be great to get `beard` on PyPI while the name is still available :dancer:

**Comment by natsheh** [comment]
Any news for making first release of beard on PyPI? I am working in a project in which I am importing some modules from beard locally.

**Comment by glouppe** [comment]
Hi. Since I left the inveniosoftware team, I lost my admin access to beard and cannot make a release myself for PyPI. 

@kaplun @jalavik @tiborsimko : the current master is good enough to be used for a release. Feel free to go ahead!

**Comment by kaplun** [comment]
AFAIK I am not admin of this repo either... I am currently on holiday, but I can check the situation next week when I am back...

**Comment by kaplun** [comment]
@tiborsimko can I become owner of the repo?

**Comment by jacenkow** [comment]
@kaplun the issues are fixed, ready to go for ```PyPi```.

**Comment by tiborsimko** [comment]
@kaplun Sure. The `beard` repository is now hosted under the `inspirehep` organisation.
