### ISSUE TITLE
float category_size in the example file

### ISSUE THREAD

**Issue by hajianOne** [inspirehep/beard#97]
Hi! I'm opening this issue as I was testing/modifying the example scripts for Python3. I see in `beard/examples/applications/author-disambiguation/sampling.py` line 197:
```
category_size = sample_size / 4
```

shouldn't this be `category_size = sample_size // 4`?
Thanks in advance for clarifying this :)

**Comment by MSusik** [comment]
@hajianOne Indeed, it should be `// 4`. Feel free to submit PR.
